name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install deps
        run: yarn install
        
      - name: Linting
        run: yarn lint

      - name: Test
        run: yarn test
        
      - name: Build
        run: yarn build
